### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by bagir** [vk-com/kphp-kdb#4]
Linux localhost.localdomain 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost kphp-kdb]# cat /etc/redhat-release
CentOS release 6.5 (Final)
[root@localhost kphp-kdb]#

[root@localhost kphp-kdb]# gcc -v
Используются внутренние спецификации.
Целевая архитектура: x86_64-redhat-linux
Параметры конфигурации: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Модель многопоточности: posix
gcc версия 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)
[root@localhost kphp-kdb]#

[root@localhost kphp-kdb]# rpm -qa|grep readline
compat-readline5-5.2-17.1.el6.x86_64
readline-static-6.0-4.el6.x86_64
compat-readline5-devel-5.2-17.1.el6.x86_64
readline-devel-6.0-4.el6.x86_64
readline-6.0-4.el6.x86_64
[root@localhost kphp-kdb]# rpm -qa|grep termcap
compat-libtermcap-2.0.8-49.el6.x86_64
compat-libtermcap-2.0.8-49.el6.i686
mingw32-termcap-1.3.1-8.el6.5.noarch
[root@localhost kphp-kdb]#

cc -Wall -O3 -m64 -march=core2 -mfpmath=sse -mssse3 -ggdb -fno-strict-aliasing -fno-strict-overflow -fwrapv  -DCOMMIT=\"f9a2f927aa97612d0c74a0e296eda8f414f13cce\" -I common -I binlog -I net -I kfs -I drinkless -I skat -I vv -I objs -I . -I/usr/include/readline5/ -c -MP -MD -MF dep/targ/targ-engine.d -MQ objs/targ/targ-engine.o -o objs/targ/targ-engine.o targ/targ-engine.c
In file included from targ/targ-engine.c:66:
objs/TL/constants.h:217:1: warning: "TL__T_E_X_T__G_E_T_M_E_S_SA_G_E_E_X_T_RA" redefined
objs/TL/constants.h:213:1: warning: this is the location of the previous definition
objs/TL/constants.h:218:1: warning: "TL__T_E_X_T__S_E_T_M_E_S_SA_G_E_E_X_T_RA" redefined
objs/TL/constants.h:214:1: warning: this is the location of the previous definition
objs/TL/constants.h:219:1: warning: "TL__T_E_X_T__I_N_C_R_M_E_S_SA_G_E_E_X_T_RA" redefined
objs/TL/constants.h:215:1: warning: this is the location of the previous definition
objs/TL/constants.h:220:1: warning: "TL__T_E_X_T__D_E_C_R_M_E_S_SA_G_E_E_X_T_RA" redefined
objs/TL/constants.h:216:1: warning: this is the location of the previous definition
targ/targ-engine.c: В функции ‘tl_do_prices’:
targ/targ-engine.c:2139: ошибка: ‘TL_TARG_PRICES_RESULT’ не описан (первое использование в этой функции)
targ/targ-engine.c:2139: ошибка: (Сообщение о неописанном идентификаторе выдается один раз
targ/targ-engine.c:2139: ошибка: для каждой функции, в которой он используется.)
targ/targ-engine.c: В функции ‘tl_do_ad_pricing’:
targ/targ-engine.c:2179: ошибка: ‘TL_TARG_PRICES_RESULT’ не описан (первое использование в этой функции)
targ/targ-engine.c: В функции ‘targ_parse_function’:
targ/targ-engine.c:3006: ошибка: ‘TL_TARG_AD_ENABLE’ не описан (первое использование в этой функции)
targ/targ-engine.c:3008: ошибка: ‘TL_TARG_AD_ENABLE_PRICE’ не описан (первое использование в этой функции)
targ/targ-engine.c:3010: ошибка: ‘TL_TARG_AD_DISABLE’ не описан (первое использование в этой функции)
targ/targ-engine.c:3012: ошибка: ‘TL_TARG_AD_SET_CTR’ не описан (первое использование в этой функции)
targ/targ-engine.c:3014: ошибка: ‘TL_TARG_AD_SET_SUMP’ не описан (первое использование в этой функции)
targ/targ-engine.c:3016: ошибка: ‘TL_TARG_AD_SET_CTR_SUMP’ не описан (первое использование в этой функции)
targ/targ-engine.c:3018: ошибка: ‘TL_TARG_AD_SET_AUD’ не описан (первое использование в этой функции)
targ/targ-engine.c:3020: ошибка: ‘TL_TARG_AD_LIMITED_VIEWS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3022: ошибка: ‘TL_TARG_AD_VIEWS_RATE_LIMIT’ не описан (первое использование в этой функции)
targ/targ-engine.c:3024: ошибка: ‘TL_TARG_AD_SITES’ не описан (первое использование в этой функции)
targ/targ-engine.c:3026: ошибка: ‘TL_TARG_AD_SET_FACTOR’ не описан (первое использование в этой функции)
targ/targ-engine.c:3028: ошибка: ‘TL_TARG_AD_SET_DOMAIN’ не описан (первое использование в этой функции)
targ/targ-engine.c:3030: ошибка: ‘TL_TARG_AD_SET_GROUP’ не описан (первое использование в этой функции)
targ/targ-engine.c:3032: ошибка: ‘TL_TARG_AD_SET_CATEGORIES’ не описан (первое использование в этой функции)
targ/targ-engine.c:3034: ошибка: ‘TL_TARG_AD_CLICKS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3036: ошибка: ‘TL_TARG_AD_CTR’ не описан (первое использование в этой функции)
targ/targ-engine.c:3038: ошибка: ‘TL_TARG_AD_SUMP’ не описан (первое использование в этой функции)
targ/targ-engine.c:3040: ошибка: ‘TL_TARG_AD_CTR_SUMP’ не описан (первое использование в этой функции)
targ/targ-engine.c:3042: ошибка: ‘TL_TARG_AD_MONEY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3044: ошибка: ‘TL_TARG_AD_VIEWS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3046: ошибка: ‘TL_TARG_AD_RECENT_VIEWS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3048: ошибка: ‘TL_TARG_RECENT_VIEWS_STATS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3050: ошибка: ‘TL_TARG_RECENT_AD_VIEWERS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3052: ошибка: ‘TL_TARG_AD_INFO’ не описан (первое использование в этой функции)
targ/targ-engine.c:3054: ошибка: ‘TL_TARG_AD_QUERY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3056: ошибка: ‘TL_TARG_USER_VIEW’ не описан (первое использование в этой функции)
targ/targ-engine.c:3058: ошибка: ‘TL_TARG_USER_GROUPS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3060: ошибка: ‘TL_TARG_USER_CLICK’ не описан (первое использование в этой функции)
targ/targ-engine.c:3062: ошибка: ‘TL_TARG_USER_FLAGS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3064: ошибка: ‘TL_TARG_USER_CLICKED_AD’ не описан (первое использование в этой функции)
targ/targ-engine.c:3066: ошибка: ‘TL_TARG_DELETE_GROUP’ не описан (первое использование в этой функции)
targ/targ-engine.c:3068: ошибка: ‘TL_TARG_TARGET’ не описан (первое использование в этой функции)
targ/targ-engine.c:3070: ошибка: ‘TL_TARG_PRICES’ не описан (первое использование в этой функции)
targ/targ-engine.c:3072: ошибка: ‘TL_TARG_AD_PRICING’ не описан (первое использование в этой функции)
targ/targ-engine.c:3074: ошибка: ‘TL_TARG_TARG_AUDIENCE’ не описан (первое использование в этой функции)
targ/targ-engine.c:3076: ошибка: ‘TL_TARG_AUDIENCE’ не описан (первое использование в этой функции)
targ/targ-engine.c:3078: ошибка: ‘TL_TARG_SEARCH’ не описан (первое использование в этой функции)
targ/targ-engine.c:3080: ошибка: ‘TL_TARG_SET_SEX’ не описан (первое использование в этой функции)
targ/targ-engine.c:3081: ошибка: ‘TL_TARG_SET_OPERATOR’ не описан (первое использование в этой функции)
targ/targ-engine.c:3082: ошибка: ‘TL_TARG_SET_BROWSER’ не описан (первое использование в этой функции)
targ/targ-engine.c:3083: ошибка: ‘TL_TARG_SET_REGION’ не описан (первое использование в этой функции)
targ/targ-engine.c:3084: ошибка: ‘TL_TARG_SET_HEIGHT’ не описан (первое использование в этой функции)
targ/targ-engine.c:3085: ошибка: ‘TL_TARG_SET_SMOKING’ не описан (первое использование в этой функции)
targ/targ-engine.c:3086: ошибка: ‘TL_TARG_SET_ALCOHOL’ не описан (первое использование в этой функции)
targ/targ-engine.c:3087: ошибка: ‘TL_TARG_SET_PPRIORITY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3088: ошибка: ‘TL_TARG_SET_IIOTHERS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3089: ошибка: ‘TL_TARG_SET_HIDDEN’ не описан (первое использование в этой функции)
targ/targ-engine.c:3090: ошибка: ‘TL_TARG_SET_CVISITED’ не описан (первое использование в этой функции)
targ/targ-engine.c:3091: ошибка: ‘TL_TARG_SET_GCOUNTRY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3092: ошибка: ‘TL_TARG_SET_PRIVACY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3093: ошибка: ‘TL_TARG_SET_POLITICAL’ не описан (первое использование в этой функции)
targ/targ-engine.c:3094: ошибка: ‘TL_TARG_SET_MSTATUS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3095: ошибка: ‘TL_TARG_SET_TIMEZONE’ не описан (первое использование в этой функции)
targ/targ-engine.c:3096: ошибка: ‘TL_TARG_SET_RATE’ не описан (первое использование в этой функции)
targ/targ-engine.c:3097: ошибка: ‘TL_TARG_SET_CUTE’ не описан (первое использование в этой функции)
targ/targ-engine.c:3098: ошибка: ‘TL_TARG_SET_FLAGS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3099: ошибка: ‘TL_TARG_SET_USER_SINGLE_GROUP_TYPE’ не описан (первое использование в этой функции)
targ/targ-engine.c:3100: ошибка: ‘TL_TARG_SET_USER_LANG’ не описан (первое использование в этой функции)
targ/targ-engine.c:3101: ошибка: ‘TL_TARG_SET_CUSTOM’ не описан (первое использование в этой функции)
targ/targ-engine.c:3103: ошибка: ‘TL_TARG_SET_RATES’ не описан (первое использование в этой функции)
targ/targ-engine.c:3105: ошибка: ‘TL_TARG_SET_USERNAME’ не описан (первое использование в этой функции)
targ/targ-engine.c:3107: ошибка: ‘TL_TARG_SET_USER_GROUP_TYPES’ не описан (первое использование в этой функции)
targ/targ-engine.c:3109: ошибка: ‘TL_TARG_SET_COUNTRY_CITY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3111: ошибка: ‘TL_TARG_SET_BIRTHDAY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3113: ошибка: ‘TL_TARG_SET_RELIGION’ не описан (первое использование в этой функции)
targ/targ-engine.c:3115: ошибка: ‘TL_TARG_SET_HOMETOWN’ не описан (первое использование в этой функции)
targ/targ-engine.c:3117: ошибка: ‘TL_TARG_SET_PROPOSAL’ не описан (первое использование в этой функции)
targ/targ-engine.c:3119: ошибка: ‘TL_TARG_SET_SCHOOL’ не описан (первое использование в этой функции)
targ/targ-engine.c:3121: ошибка: ‘TL_TARG_SET_EDUCATION’ не описан (первое использование в этой функции)
targ/targ-engine.c:3123: ошибка: ‘TL_TARG_SET_COMPANY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3125: ошибка: ‘TL_TARG_SET_MILITARY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3127: ошибка: ‘TL_TARG_SET_ADDRESS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3129: ошибка: ‘TL_TARG_SET_INTEREST’ не описан (первое использование в этой функции)
targ/targ-engine.c:3131: ошибка: ‘TL_TARG_SET_USER_GROUP’ не описан (первое использование в этой функции)
targ/targ-engine.c:3133: ошибка: ‘TL_TARG_DELETE_USER’ не описан (первое использование в этой функции)
targ/targ-engine.c:3135: ошибка: ‘TL_TARG_DELETE_EDUCATION’ не описан (первое использование в этой функции)
targ/targ-engine.c:3136: ошибка: ‘TL_TARG_DELETE_SCHOOLS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3137: ошибка: ‘TL_TARG_DELETE_WORK’ не описан (первое использование в этой функции)
targ/targ-engine.c:3138: ошибка: ‘TL_TARG_DELETE_ADDRESSES’ не описан (первое использование в этой функции)
targ/targ-engine.c:3139: ошибка: ‘TL_TARG_DELETE_MILITARY’ не описан (первое использование в этой функции)
targ/targ-engine.c:3140: ошибка: ‘TL_TARG_DELETE_GROUPS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3141: ошибка: ‘TL_TARG_DELETE_POSITIVE_GROUPS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3142: ошибка: ‘TL_TARG_DELETE_NEGATIVE_GROUPS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3143: ошибка: ‘TL_TARG_DELETE_LANGS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3144: ошибка: ‘TL_TARG_DELETE_PROPOSAL’ не описан (первое использование в этой функции)
targ/targ-engine.c:3145: ошибка: ‘TL_TARG_DELETE_INTERESTS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3147: ошибка: ‘TL_TARG_DELETE_USER_GROUP’ не описан (первое использование в этой функции)
targ/targ-engine.c:3149: ошибка: ‘TL_TARG_DELETE_USER_GROUPS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3151: ошибка: ‘TL_TARG_SET_USER_GROUPS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3153: ошибка: ‘TL_TARG_ADD_USER_GROUPS’ не описан (первое использование в этой функции)
targ/targ-engine.c:3155: ошибка: ‘TL_TARG_USER_VISIT’ не описан (первое использование в этой функции)
targ/targ-engine.c:3157: ошибка: ‘TL_TARG_DELETE_USER_LANG’ не описан (первое использование в этой функции)
targ/targ-engine.c:3159: ошибка: ‘TL_WEIGHTS_SEND_SMALL_UPDATES’ не описан (первое использование в этой функции)
targ/targ-engine.c:3161: ошибка: ‘TL_WEIGHTS_SEND_UPDATES’ не описан (первое использование в этой функции)
targ/targ-engine.c:3163: ошибка: ‘TL_TARG_USER_ADS’ не описан (первое использование в этой функции)
make: **\* [objs/targ/targ-engine.o] Ошибка 1

**Comment by vk-com** [comment]
Seems to be locale issue in awk. Please try again.

**Comment by bagir** [comment]
fixed. thx.
